Adding two numbers
js-tasks-ru/jsbasic-20200903_nataliia-melezhyk pull request #1
Opened 2020-09-03 11:21 UTC by nataliiamelezhik

2020-09-03 11:29 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-07 07:21 UTC, koalex requested changes
Удали стр 12 и 13

2020-09-07 07:21 UTC, koalex commented on 0-module/1-task/index.js
> +sum(1,1);
Удали строку 12 и 13

2020-09-07 10:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-07 11:01 UTC, nataliiamelezhik commented on 0-module/1-task/index.js
> +sum(1,1);
Готово

2020-09-07 11:08 UTC, koalex approved these changes
Всё ОК

2020-09-07 11:09 UTC, merged