arrayNames
js-tasks-ru/jsbasic-20200903_nataliia-melezhyk pull request #8
Opened 2020-09-15 10:51 UTC by nataliiamelezhik

2020-09-15 10:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-15 13:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-16 12:37 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-16 14:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
```
```diff
Функция showSalary(users, age)
- для пользователей до 40 лет должна вывести строку с зарплатами
- для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```

2020-09-17 12:32 UTC, koalex approved these changes

2020-09-17 12:32 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-09-17 12:33 UTC, koalex requested changes
проверь чтобы `npm test` не выдавал ошибок

2020-09-17 20:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-19 07:26 UTC, koalex approved these changes
ok

2020-09-19 07:27 UTC, merged